### ISSUE TITLE
Type problem with `and`

### ISSUE THREAD

**Issue by Frikki** [TylorS167/167#8]
**Code to reproduce the issue:**

```typescript
function test(a: boolean, b: boolean): boolean {
  return and(a, b)
}
```

**Expected behavior:**

No type errors.

**Actual behavior:**

> [ts] Argument of type 'boolean' is not assignable to parameter of type 'true'.

**Versions of packages used:**

0.37.0

**Comment by TylorS** [comment]
Should be fixed in v0.38.0
